import { uniqueNamesGenerator, adjectives, colors, animals } from 'unique-names-generator';

/**
 * Generate a UUIDv4.
 * 
 * @returns A UUIDv4 as a string.
 */
export const uuidv4 = () => {
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, c => {
    const r = crypto.getRandomValues(new Uint8Array(1))[0] & 15;
    const v = c === 'x' ? r : (r & 0x3) | 0x8;
    return v.toString(16);
  });
};

/**
 * Generate a random name consisting out of an adjective, color and animal.
 * 
 * @returns A raondom name.
 */
export const randomName = () => {
  const computerParts = [
    'Hard Disk Drive',
    'Power Supply',
    'Solar Panel',
    'RAM stick',
    'Capacitor',
    'Resistor',
    'Diode',
    'Transistor',
    'Microcontroller',
    'Microprocessor',
    'Motherboard',
    'GPU',
    'CPU',
    'SSD',
    'Ethernet Cable',
    'Wi-Fi Module',
    'Bluetooth Module',
    'OLED Display',
    'LCD Screen',
    'Touchscreen',
    'Keyboard',
    'Mouse',
    'Trackpad',
    'Power Adapter',
    'Fan',
    'Heatsink',
    'Thermal Paste',
    'PCB',
    'Breadboard',
    'Arduino',
    'Raspberry Pi',
    'ESP32',
    'Graphics Card',
    'NFC Tag',
    'RFID Reader',
    'Ultrasonic Sensor',
    'Temperature Sensor',
    'Humidity Sensor',
    'Gas Sensor',
    'Pressure Sensor',
    'Accelerometer',
    'Gyroscope',
    'Magnetometer',
    'Light Sensor',
    'Infrared Sensor',
    'Camera Module',
    'Microphone',
    'Speaker',
    'Piezo Buzzer',
    'Relay',
    'Motor',
    'Servo Motor',
    'Stepper Motor',
    'Battery',
    'Li-Ion Battery',
    'Lithium Battery',
    'AA Battery',
    'Energy Harvester',
    'Voltage Regulator',
    'Current Sensor',
    'Voltage Sensor',
    'Power Switch',
    'Push Button',
    'Rotary Encoder',
    'Potentiometer',
    'OLED Controller',
    'Display Driver',
    'Signal Amplifier',
    'Logic Gate',
    'FPGA',
    'ASIC',
    'Heat Pipe',
    'Cooling Fan',
    'Cable Connector',
    'USB Hub',
    'USB Cable',
    'HDMI Cable',
    'VGA Cable',
    'DVI Cable',
    'RJ45 Connector',
    'SMA Connector',
    'Antenna',
    'LoRa Module',
    'Zigbee Module',
    'NB-IoT Module',
    'LTE-M Module',
    'SIM Card',
    'eSIM',
    'iSIM',
    'RTC Module',
    'EEPROM',
    'Flash Memory',
    'SD Card',
    'MicroSD Card',
    'Wi-Fi Antenna',
    'RFID Tag',
    'PCB Trace',
    'Solder Mask',
    'Via',
    'Connector Pin',
    'Header Pin',
    'CPU',
    'VGA connector',
    'Socket',
    'Chipset',
    'Clock Oscillator',
    'Crystal',
    'Voltage Divider',
    'Current Limiter',
    'Fuse',
    'Inductor',
    'Transformer',
    'Switch',
    'Button',
    'Joystick',
    'LED',
    'RGB LED',
    'Infrared LED',
    'Photodiode',
    'Optocoupler',
    'Buzzer',
    'Piezo Element',
    'Microcontroller Board',
    'Single-board Computer',
    'Embedded System',
    'IoT Gateway',
    'Modem',
    'Router',
    'Access Point',
    'Repeater',
    'Signal Booster',
    'Cloud Server',
    'Edge Device',
    'Sensor Node',
    'Actuator',
    'Transceiver',
    'Multiplexer',
    'Demultiplexer',
    'Voltage Converter',
    'Current Transformer',
    'Digital Signal Processor',
    'Analog-to-Digital Converter',
    'Digital-to-Analog Converter',
    'Power Amplifier',
    'Operational Amplifier',
    'Logic Analyzer',
    'Oscilloscope',
    'Multimeter',
    'Network Switch',
    'Patch Panel',
    'Cable Management',
    'Heat Sink Compound',
    'Thermal Pad',
    'Protective Case',
    'Enclosure',
    'DIN Rail',
    'Mounting Bracket',
    'Terminal Block',
    'Busbar',
    'Connector Block',
    'PCB Mount',
    'Breadboard Jumper',
    'Ribbon Cable',
    'Flex Cable',
    'Servo Driver',
    'Motor Driver',
    'Power Module',
    'Sensor Module',
    'Communication Module',
    'Wireless Module',
    'IoT Node',
    'Gateway Module',
    'Edge Controller'
  ];

  const randName = uniqueNamesGenerator({
    dictionaries: [colors, computerParts],
    separator: ' ',
    style: 'capital'
  });

  return randName;
};